### ISSUE TITLE
TypeError: When doing npm start

### ISSUE THREAD

**Issue by ankitiitb1069** [actionhero/actionhero#1011] opened 2017-03-02 06:20 UTC
# Name of Issue
Description of Issue

I get the following error when I do npm start

`/home/ankit/actionhero-tutorial/node_modules/actionhero/node_modules/primus/index.js:288
        throw e;
        ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/home/ankit/actionhero-tutorial/node_modules/actionhero/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ankit/actionhero-tutorial/node_modules/actionhero/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:409:26)`

- ActionHero Version: `16.0.2`
- Node.js Version: `4.4.2`
- Operating System `Ubuntu 16.04`

# Steps to reproduce your error
- Create a new project actionhero-tutorial 
- Install actionhero `npm install actionhero`
- Run  `./node_modules/.bin/actionhero generate`
- Run `npm install` and then `npm start`

---

If your "issue" does not fit into this template, it might not be an issue!  Please join our [slack team](http://slack.actionherojs.com) and ask the question of the community there.

**Comment by evantahler** [comment] 2017-03-03 05:15
I am unable to reproduce this on OSX with node version `v4.6.1` and actionhero v16.0.2.  Can anyone else?

**Comment by kytwb** [comment] 2017-03-07 04:20
`You need Node.js 4.5.0 or greater if you are using ws@2`  
See https://github.com/websockets/ws/issues/998#issuecomment-279144218

**Comment by evantahler** [comment] 2017-03-07 04:50
Ah! Thanks for finding the @kytwb for finding the reference. Closing

**Closed by evantahler** 2017-03-07 04:50 UTC

**Comment by kytwb** [comment] 2017-03-07 04:55
@evantahler should I submit a PR updating node engine requirement?

**Comment by evantahler** [comment] 2017-03-07 06:03
This is tough because `ws` is optional, and there are other underlying web socket transports which can be used though primus.  I don't want to drop support for LTS node.  At the very least we should have a note on the site about this.  

I think we should solicit input on the Slack channel.
