### ISSUE TITLE
Uncaught Error: fakeredis: You've closed this connection with QUIT, cannot SET

### ISSUE THREAD

**Issue by witem** [actionhero/actionhero#1028] opened 2017-03-27 19:50 UTC
# Uncaught Error: fakeredis: You've closed this connection with QUIT, cannot SET
Fakeredis error in tests on call actionhero restart.
Stack trace:
```
Uncaught Error: fakeredis: You've closed this connection with QUIT, cannot GET
      at CLOSED (node_modules/fakeredis/lib/connection.js:244:11)
      at push (node_modules/fakeredis/lib/connection.js:16:5)
      at RedisClient.cl.send_command (node_modules/fakeredis/main.js:151:7)
      at RedisClient.(anonymous function).RedisClient.(anonymous function) (node_modules/redis/lib/commands.js:45:25)
      at node_modules/node-resque/lib/connection.js:44:18
      at node_modules/async/dist/async.js:3791:9
      at replenish (node_modules/async/dist/async.js:882:17)
      at iterateeCallback (node_modules/async/dist/async.js:867:17)
      at node_modules/async/dist/async.js:844:16
      at node_modules/async/dist/async.js:3796:13
      at apply (node_modules/async/dist/async.js:21:25)
      at node_modules/async/dist/async.js:56:12
      at node_modules/fakeredis/main.js:195:5
      at Timeout._onTimeout (node_modules/fakeredis/lib/connection.js:343:18)
```
It`s broke on actionhero test:
>  Test: Task Middleware
>     **1) can modify parameters before a task and modify result after task completion**
> 
>   Test: RunAction
>     **2) "before all" hook**
> 
>   Utils
>     **3) "before all" hook**

**Reproduced not always**

### Environment
- ActionHero Version: `16.0.2`
- Node.js Version: `6.10.0`
- Operating System `(Ubuntu 16, Arch linux and Solaris)`

# Steps to reproduce your error
- run mocha test where call many `actionheroServer.restart`

**Comment by evantahler** [comment] 2017-03-28 01:27
I've been testing on your configuration: node v6, ubuntu (+ OSX), and I can't reproduce this... can anyone else?

**Comment by vladbalmos** [comment] 2017-03-30 18:41
I can reproduce it in a vagrant machine (ubuntu/xenial64) using node v6.10.1:
[Vagrantfile.txt](https://github.com/actionhero/actionhero/files/883447/Vagrantfile.txt)
```
ubuntu@ubuntu-xenial:/vagrant$ NODE_ENV=test node_modules/.bin/mocha test/tasks/

Test: Task Middleware
test-server-10883 @ 2017-03-30T18:36:28.372Z - notice: *** Starting ActionHero ***
test-server-10883 @ 2017-03-30T18:36:28.658Z - notice: pid: 10883
test-server-10883 @ 2017-03-30T18:36:28.659Z - notice: server ID: test-server-10883
test-server-10883 @ 2017-03-30T18:36:28.661Z - info: ensuring the existence of the chatRoom: defaultRoom
test-server-10883 @ 2017-03-30T18:36:28.661Z - info: ensuring the existence of the chatRoom: otherRoom
test-server-10883 @ 2017-03-30T18:36:28.667Z - info: actionhero member test-server-10883 has joined the cluster
test-server-10883 @ 2017-03-30T18:36:28.671Z - notice: Starting server: `socket` @ 0.0.0.0:11884
test-server-10883 @ 2017-03-30T18:36:28.675Z - notice: Starting server: `web` @ 0.0.0.0:11883
test-server-10883 @ 2017-03-30T18:36:28.681Z - notice: Starting server: `websocket`
test-server-10883 @ 2017-03-30T18:36:29.450Z - warning: loading the testServer
test-server-10883 @ 2017-03-30T18:36:29.451Z - notice: environment: test
test-server-10883 @ 2017-03-30T18:36:29.451Z - alert: *** ActionHero Started ***
    1) can modify parameters before a task and modify result after task completion
test-server-10883 @ 2017-03-30T18:36:29.762Z - notice: Shutting down open servers and stopping task processing...
test-server-10883 @ 2017-03-30T18:36:29.763Z - notice: Stopping server: socket
test-server-10883 @ 2017-03-30T18:36:29.764Z - notice: Stopping server: web
test-server-10883 @ 2017-03-30T18:36:29.764Z - notice: Stopping server: websocket
test-server-10883 @ 2017-03-30T18:36:29.767Z - alert: *** ActionHero Stopped ***

  Test: RunAction
test-server-10883 @ 2017-03-30T18:36:29.848Z - notice: *** Starting ActionHero ***
test-server-10883 @ 2017-03-30T18:36:29.870Z - notice: pid: 10883
test-server-10883 @ 2017-03-30T18:36:29.871Z - notice: server ID: test-server-10883
test-server-10883 @ 2017-03-30T18:36:29.871Z - info: ensuring the existence of the chatRoom: defaultRoom
test-server-10883 @ 2017-03-30T18:36:29.872Z - info: ensuring the existence of the chatRoom: otherRoom
test-server-10883 @ 2017-03-30T18:36:29.873Z - info: actionhero member test-server-10883 has left the cluster
    2) "before all" hook
test-server-10883 @ 2017-03-30T18:36:29.876Z - notice: Shutting down open servers and stopping task processing...
test-server-10883 @ 2017-03-30T18:36:29.877Z - notice: Stopping server: socket
test-server-10883 @ 2017-03-30T18:36:29.877Z - notice: Stopping server: web
test-server-10883 @ 2017-03-30T18:36:29.878Z - notice: Stopping server: websocket
test-server-10883 @ 2017-03-30T18:36:29.880Z - alert: *** ActionHero Stopped ***

test-server-10883 @ 2017-03-30T18:36:29.881Z - info: actionhero member test-server-10883 has joined the cluster
  3) "after all" hook

  0 passing (2s)
  3 failing

  1) Test: Task Middleware can modify parameters before a task and modify result after task completion:
     Uncaught Error: Uncaught, unspecified "error" event. (null)
      at queue.<anonymous> (node_modules/node-resque/lib/worker.js:35:10)
      at connection.<anonymous> (node_modules/node-resque/lib/queue.js:17:10)
      at Redis.self.listeners.error (node_modules/node-resque/lib/connection.js:87:48)
      at Redis.silentEmit (node_modules/ioredis/lib/redis.js:472:22)
      at Socket.<anonymous> (node_modules/ioredis/lib/redis/event_handler.js:114:10)
      at emitErrorNT (net.js:1281:8)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  2) Test: RunAction "before all" hook:
     Uncaught Error: Uncaught, unspecified "error" event. (null)
      at queue.<anonymous> (node_modules/node-resque/lib/worker.js:35:10)
      at connection.<anonymous> (node_modules/node-resque/lib/queue.js:17:10)
      at Redis.self.listeners.error (node_modules/node-resque/lib/connection.js:87:48)
      at Redis.silentEmit (node_modules/ioredis/lib/redis.js:472:22)
      at Socket.<anonymous> (node_modules/ioredis/lib/redis/event_handler.js:114:10)
      at emitErrorNT (net.js:1281:8)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  3) Test: RunAction "after all" hook:
     Uncaught Error: fakeredis: You've closed this connection with QUIT, cannot GET
      at CLOSED (node_modules/fakeredis/lib/connection.js:244:11)
      at push (node_modules/fakeredis/lib/connection.js:16:5)
      at RedisClient.cl.send_command (node_modules/fakeredis/main.js:151:7)
      at RedisClient.(anonymous function).RedisClient.(anonymous function) (node_modules/redis/lib/commands.js:45:25)
      at node_modules/node-resque/lib/connection.js:44:18
      at node_modules/async/dist/async.js:3791:9
      at replenish (node_modules/async/dist/async.js:882:17)
      at iterateeCallback (node_modules/async/dist/async.js:867:17)
      at node_modules/async/dist/async.js:844:16
      at node_modules/async/dist/async.js:3796:13
      at apply (node_modules/async/dist/async.js:21:25)
      at node_modules/async/dist/async.js:56:12
      at node_modules/fakeredis/main.js:195:5
      at Timeout._onTimeout (node_modules/fakeredis/lib/connection.js:343:18)
```

**Comment by evantahler** [comment] 2017-04-06 04:04
I'm going to close this in favor of https://github.com/actionhero/actionhero/issues/1034

**Closed by evantahler** 2017-04-06 04:04 UTC
